name: Maven Automated Testing

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./PROG6112_Assignment1_ST10522119

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Display Java Version
        run: java -version

      - name: Build Maven Project
        run: mvn --batch-mode -DskipTests package

      - name: Run Maven Tests
        run: mvn --batch-mode test
